export interface BlueprintAnswers {
  target_audience?: string;
  timeline?: string;
  budget?: string;
  technical_skills?: string;
  main_goal?: string;
}

export function generateBlueprintTemplate(
  idea: string,
  answers: BlueprintAnswers
): string {
  return `# Project Blueprint

## Original Idea
${idea}

## Clarified Requirements

### Target Audience
${answers.target_audience || 'Not specified'}

### Timeline
${answers.timeline || 'Not specified'}

### Budget
${answers.budget || 'Not specified'}

### Technical Skills
${answers.technical_skills || 'Not specified'}

### Main Goal
${answers.main_goal || 'Not specified'}

## Action Plan

### Phase 1: Foundation (Week 1-2)
- [ ] Research and planning
- [ ] Define technical requirements
- [ ] Set up development environment
- [ ] Create basic project structure

### Phase 2: Core Development (Week 3-4)
- [ ] Implement main features
- [ ] Set up database schema
- [ ] Create user interface
- [ ] Basic testing

### Phase 3: Refinement (Week 5-6)
- [ ] User testing and feedback
- [ ] Bug fixes and improvements
- [ ] Performance optimization
- [ ] Documentation

### Phase 4: Launch (Week 7-8)
- [ ] Final testing
- [ ] Deployment preparation
- [ ] Launch and monitoring
- [ ] Post-launch support

## Resources Needed
- Development tools and software
- Design assets (if applicable)
- Testing environment
- Deployment platform

## Success Metrics
- User engagement and feedback
- Performance benchmarks
- Feature completion rate
- Timeline adherence

---
*Generated by IdeaFlow on ${new Date().toLocaleDateString()}*
`;
}
