import {
  RetryConfig,
  CircuitBreakerOptions,
  ServiceResilienceConfig,
  ResilienceConfig,
} from './types';
import { RESILIENCE_CONFIG } from '../config/constants';

export const DEFAULT_RETRIES: RetryConfig = {
  maxRetries: RESILIENCE_CONFIG.RETRY.DEFAULT_MAX_RETRIES,
  initialDelayMs: RESILIENCE_CONFIG.RETRY.DEFAULT_BASE_DELAY_MS,
  maxDelayMs: RESILIENCE_CONFIG.RETRY.DEFAULT_MAX_DELAY_MS,
  backoffMultiplier: RESILIENCE_CONFIG.RETRY.DEFAULT_BACKOFF_MULTIPLIER,
};

export const DEFAULT_TIMEOUTS: Record<string, number> = {
  openai: RESILIENCE_CONFIG.TIMEOUTS.OPENAI,
  notion: RESILIENCE_CONFIG.TIMEOUTS.NOTION,
  trello: RESILIENCE_CONFIG.TIMEOUTS.TRELLO,
  github: RESILIENCE_CONFIG.TIMEOUTS.GITHUB,
  database: RESILIENCE_CONFIG.TIMEOUTS.DATABASE,
};

export const DEFAULT_CIRCUIT_BREAKER_CONFIG: CircuitBreakerOptions = {
  failureThreshold: RESILIENCE_CONFIG.CIRCUIT_BREAKER.DEFAULT_FAILURE_THRESHOLD,
  resetTimeoutMs: RESILIENCE_CONFIG.CIRCUIT_BREAKER.DEFAULT_RESET_TIMEOUT_MS,
  monitoringPeriodMs:
    RESILIENCE_CONFIG.CIRCUIT_BREAKER.DEFAULT_MONITORING_PERIOD_MS,
};

export const defaultResilienceConfigs: Record<string, ServiceResilienceConfig> =
  {
    openai: {
      retry: RESILIENCE_CONFIG.SERVICE_RETRY.OPENAI,
      timeout: { timeoutMs: RESILIENCE_CONFIG.TIMEOUTS.OPENAI },
      circuitBreaker: RESILIENCE_CONFIG.SERVICE_CIRCUIT_BREAKER.OPENAI,
    },
    github: {
      retry: RESILIENCE_CONFIG.SERVICE_RETRY.GITHUB,
      timeout: { timeoutMs: RESILIENCE_CONFIG.TIMEOUTS.GITHUB },
      circuitBreaker: RESILIENCE_CONFIG.SERVICE_CIRCUIT_BREAKER.GITHUB,
    },
    notion: {
      retry: RESILIENCE_CONFIG.SERVICE_RETRY.NOTION,
      timeout: { timeoutMs: RESILIENCE_CONFIG.TIMEOUTS.NOTION },
      circuitBreaker: RESILIENCE_CONFIG.SERVICE_CIRCUIT_BREAKER.NOTION,
    },
    trello: {
      retry: RESILIENCE_CONFIG.SERVICE_RETRY.TRELLO,
      timeout: { timeoutMs: RESILIENCE_CONFIG.TIMEOUTS.TRELLO },
      circuitBreaker: RESILIENCE_CONFIG.SERVICE_CIRCUIT_BREAKER.TRELLO,
    },
    supabase: {
      retry: RESILIENCE_CONFIG.SERVICE_RETRY.SUPABASE,
      timeout: { timeoutMs: RESILIENCE_CONFIG.TIMEOUTS.SUPABASE },
      circuitBreaker: RESILIENCE_CONFIG.SERVICE_CIRCUIT_BREAKER.SUPABASE,
    },
  };

export const DEFAULT_RESILIENCE_CONFIG: ResilienceConfig = {
  timeoutMs: RESILIENCE_CONFIG.TIMEOUTS.DEFAULT,
  maxRetries: RESILIENCE_CONFIG.RETRY.DEFAULT_MAX_RETRIES,
  baseDelayMs: RESILIENCE_CONFIG.RETRY.DEFAULT_BASE_DELAY_MS,
  maxDelayMs: RESILIENCE_CONFIG.RETRY.DEFAULT_MAX_DELAY_MS,
  failureThreshold: RESILIENCE_CONFIG.CIRCUIT_BREAKER.DEFAULT_FAILURE_THRESHOLD,
  resetTimeoutMs: RESILIENCE_CONFIG.CIRCUIT_BREAKER.DEFAULT_RESET_TIMEOUT_MS,
};
