'use client';

import { useState, useEffect } from 'react';

interface BlueprintDisplayProps {
  idea: string;
  answers: Record<string, string>;
}

export default function BlueprintDisplay({
  idea,
  answers,
}: BlueprintDisplayProps) {
  const [isGenerating, setIsGenerating] = useState(true);
  const [blueprint, setBlueprint] = useState('');

  // Simulate blueprint generation
  useEffect(() => {
    const generateBlueprint = async () => {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      const generatedBlueprint = `# Project Blueprint

## Original Idea
${idea}

## Clarified Requirements

### Target Audience
${answers.target_audience || 'Not specified'}

### Timeline
${answers.timeline || 'Not specified'}

### Budget
${answers.budget || 'Not specified'}

### Technical Skills
${answers.technical_skills || 'Not specified'}

### Main Goal
${answers.main_goal || 'Not specified'}

## Action Plan

### Phase 1: Foundation (Week 1-2)
- [ ] Research and planning
- [ ] Define technical requirements
- [ ] Set up development environment
- [ ] Create basic project structure

### Phase 2: Core Development (Week 3-4)
- [ ] Implement main features
- [ ] Set up database schema
- [ ] Create user interface
- [ ] Basic testing

### Phase 3: Refinement (Week 5-6)
- [ ] User testing and feedback
- [ ] Bug fixes and improvements
- [ ] Performance optimization
- [ ] Documentation

### Phase 4: Launch (Week 7-8)
- [ ] Final testing
- [ ] Deployment preparation
- [ ] Launch and monitoring
- [ ] Post-launch support

## Resources Needed
- Development tools and software
- Design assets (if applicable)
- Testing environment
- Deployment platform

## Success Metrics
- User engagement and feedback
- Performance benchmarks
- Feature completion rate
- Timeline adherence

---
*Generated by IdeaFlow on ${new Date().toLocaleDateString()}*
`;

      setBlueprint(generatedBlueprint);
      setIsGenerating(false);
    };

    generateBlueprint();
  }, [idea, answers]);

  const handleDownload = () => {
    const blob = new Blob([blueprint], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'project-blueprint.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isGenerating) {
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        <div
          className="bg-white rounded-lg shadow-lg p-6 sm:p-8"
          role="status"
          aria-live="polite"
          aria-label="Generating your blueprint"
        >
          <div className="space-y-6">
            <div className="flex items-center space-x-4">
              <div
                className="animate-spin rounded-full h-10 w-10 sm:h-12 sm:w-12 border-4 border-primary-600 border-t-transparent"
                aria-hidden="true"
              ></div>
              <div>
                <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mb-1">
                  Generating Your Blueprint...
                </h2>
                <p className="text-sm sm:text-base text-gray-600">
                  Our AI is analyzing your answers and creating a detailed
                  action plan.
                </p>
              </div>
            </div>

            <div className="space-y-4 pt-4 border-t border-gray-200">
              <div className="skeleton-text-lg h-6 w-2/3"></div>
              <div className="space-y-2">
                <div className="skeleton-text h-4 w-full"></div>
                <div className="skeleton-text h-4 w-11/12"></div>
                <div className="skeleton-text h-4 w-4/5"></div>
              </div>

              <div className="pt-4 border-t border-gray-200">
                <div className="skeleton-text h-5 w-1/2 mb-2"></div>
                <div className="space-y-2 pl-4">
                  <div className="flex items-start space-x-2">
                    <div className="skeleton w-5 h-5 rounded flex-shrink-0"></div>
                    <div className="skeleton-text h-4 flex-1"></div>
                  </div>
                  <div className="flex items-start space-x-2">
                    <div className="skeleton w-5 h-5 rounded flex-shrink-0"></div>
                    <div className="skeleton-text h-4 flex-1"></div>
                  </div>
                  <div className="flex items-start space-x-2">
                    <div className="skeleton w-5 h-5 rounded flex-shrink-0"></div>
                    <div className="skeleton-text h-4 flex-1"></div>
                  </div>
                </div>
              </div>

              <div className="pt-4 border-t border-gray-200 flex justify-between items-center">
                <div className="skeleton-text h-4 w-1/3"></div>
                <div className="space-x-3">
                  <div className="skeleton-button w-24 inline-block"></div>
                  <div className="skeleton-button w-32 inline-block"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <article className="bg-white rounded-lg shadow-lg">
        <header className="border-b border-gray-200 px-4 sm:px-8 py-4 sm:py-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <h2 className="text-xl sm:text-2xl font-semibold text-gray-900">
              Your Project Blueprint
            </h2>
            <button
              onClick={handleDownload}
              className="btn btn-primary"
              aria-label="Download blueprint as Markdown file"
            >
              Download Markdown
            </button>
          </div>
        </header>

        <main className="p-4 sm:p-8">
          <div className="prose prose-sm sm:prose-lg max-w-none">
            <pre
              className="whitespace-pre-wrap font-mono text-xs sm:text-sm text-gray-800 bg-gray-50 p-4 sm:p-6 rounded-lg overflow-x-auto"
              role="textbox"
              aria-label="Blueprint content"
              tabIndex={0}
            >
              {blueprint}
            </pre>
          </div>
        </main>

        <footer className="border-t border-gray-200 px-4 sm:px-8 py-4 sm:py-6 bg-gray-50">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <p className="text-xs sm:text-sm text-gray-600">
              Ready to start implementing? Share this blueprint with your team
              or keep it as your guide.
            </p>
            <nav
              className="flex sm:space-x-4 space-y-2 sm:space-y-0 flex-col sm:flex-row"
              aria-label="Blueprint actions"
            >
              <button
                type="button"
                className="btn btn-secondary"
                aria-label="Start over with a new idea"
              >
                Start Over
              </button>
              <button
                type="button"
                className="btn btn-primary"
                aria-label="Export blueprint to external tools"
              >
                Export to Tools
              </button>
            </nav>
          </div>
        </footer>
      </article>
    </div>
  );
}
