'use client';

import { useState, useEffect } from 'react';

interface BlueprintDisplayProps {
  idea: string;
  answers: Record<string, string>;
}

export default function BlueprintDisplay({
  idea,
  answers,
}: BlueprintDisplayProps) {
  const [isGenerating, setIsGenerating] = useState(true);
  const [blueprint, setBlueprint] = useState('');

  // Simulate blueprint generation
  useEffect(() => {
    const generateBlueprint = async () => {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      const generatedBlueprint = `# Project Blueprint

## Original Idea
${idea}

## Clarified Requirements

### Target Audience
${answers.target_audience || 'Not specified'}

### Timeline
${answers.timeline || 'Not specified'}

### Budget
${answers.budget || 'Not specified'}

### Technical Skills
${answers.technical_skills || 'Not specified'}

### Main Goal
${answers.main_goal || 'Not specified'}

## Action Plan

### Phase 1: Foundation (Week 1-2)
- [ ] Research and planning
- [ ] Define technical requirements
- [ ] Set up development environment
- [ ] Create basic project structure

### Phase 2: Core Development (Week 3-4)
- [ ] Implement main features
- [ ] Set up database schema
- [ ] Create user interface
- [ ] Basic testing

### Phase 3: Refinement (Week 5-6)
- [ ] User testing and feedback
- [ ] Bug fixes and improvements
- [ ] Performance optimization
- [ ] Documentation

### Phase 4: Launch (Week 7-8)
- [ ] Final testing
- [ ] Deployment preparation
- [ ] Launch and monitoring
- [ ] Post-launch support

## Resources Needed
- Development tools and software
- Design assets (if applicable)
- Testing environment
- Deployment platform

## Success Metrics
- User engagement and feedback
- Performance benchmarks
- Feature completion rate
- Timeline adherence

---
*Generated by IdeaFlow on ${new Date().toLocaleDateString()}*
`;

      setBlueprint(generatedBlueprint);
      setIsGenerating(false);
    };

    generateBlueprint();
  }, [idea, answers]);

  const handleDownload = () => {
    const blob = new Blob([blueprint], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'project-blueprint.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isGenerating) {
    return (
      <div
        className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12"
        role="status"
        aria-live="polite"
      >
        <div className="text-center">
          <div
            className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"
            aria-hidden="true"
          ></div>
          <h2 className="text-2xl font-semibold text-gray-900 mb-2">
            Generating Your Blueprint...
          </h2>
          <p className="text-gray-600">
            Our AI is analyzing your answers and creating a detailed action
            plan.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <section
        aria-labelledby="blueprint-heading"
        className="bg-white rounded-lg shadow-lg"
      >
        <header className="border-b border-gray-200 px-8 py-6">
          <div className="flex justify-between items-center">
            <h2
              id="blueprint-heading"
              className="text-2xl font-semibold text-gray-900"
            >
              Your Project Blueprint
            </h2>
            <button
              onClick={handleDownload}
              className="btn btn-primary"
              aria-label="Download blueprint as Markdown file"
            >
              Download Markdown
            </button>
          </div>
        </header>

        <div className="p-8">
          <div className="prose prose-lg max-w-none">
            <pre
              className="whitespace-pre-wrap font-mono text-sm text-gray-800 bg-gray-50 p-6 rounded-lg overflow-x-auto"
              aria-label="Generated project blueprint content"
              tabIndex={0}
            >
              {blueprint}
            </pre>
          </div>
        </div>

        <footer className="border-t border-gray-200 px-8 py-6 bg-gray-50">
          <div className="flex justify-between items-center">
            <p className="text-sm text-gray-600">
              Ready to start implementing? Share this blueprint with your team
              or keep it as your guide.
            </p>
            <div className="space-x-4">
              <button
                className="btn btn-secondary"
                aria-label="Start over with a new idea"
              >
                Start Over
              </button>
              <button
                className="btn btn-primary"
                aria-label="Export blueprint to project management tools"
              >
                Export to Tools
              </button>
            </div>
          </div>
        </footer>
      </section>
    </div>
  );
}
