#!/bin/bash
# Stale Branch Cleanup Script
# Generated by RepoKeeper on 2026-08-20

set -e

echo "=== Stale Branch Cleanup ==="
echo "Date: $(date)"
echo ""

# List of stale branches to delete (older than 7 days, not merged)
STALE_BRANCHES=(
    # Agent runs (Aug 5-9)
    "origin/agent-11117281909301655948"
    "origin/agent-13324414300462826408"
    "origin/agent-14441268146792344491"
    "origin/agent-16483920743327301593"
    "origin/agent-18292173401585082377"
    "origin/agent-657115115429537147"
    
    # Jules automated branches (Aug 5-11)
    "origin/jules-4095694043641441462-78dac0ce"
    "origin/jules-909067143245484999-40165ac9"
    "origin/jules-11996386994298700519-76d0dc4a"
    "origin/jules-12356495622633248920-e3748322"
    "origin/jules-10260988973601272278-016c65cf"
    "origin/jules-11769130672378869469-d1c9fddb"
    "origin/jules-3507986072740563866-3f2912b7"
    "origin/jules-5091086911110183271-d35db73c"
    "origin/jules-17307420779572656952-0ef6bfc8"
    "origin/jules-14152406296390904113-bd5591f5"
    
    # Old Bolt optimizations (Aug 6-7)
    "origin/bolt/opt-visual-id-generation-12725574570215761056"
    "origin/bolt/dom-utils-opt-3846342459060544931"
    "origin/bolt/sanitize-object-perf-16584290654635769266"
    
    # Old BroCula branches (Aug 6-7)
    "origin/brocula/browser-console-optimize"
    "origin/brocula/browser-console-lighthouse-20260807-0051"
    "origin/brocula/browser-console-audit-20260807-1639"
    "origin/brocula/perf-optimization-20260807-0848"
    
    # Old Palette branches (Aug 6-7)
    "origin/palette/capslock-fadeout-ux-20260806"
    "origin/palette/micro-ux-footer-scroll-top-20260807"
    
    # Old bugfix branches (Aug 7)
    "origin/bugfix/toast-a11y-button-memory-20260807-164300"
    "origin/fix/circuit-breaker-race-condition-597"
    
    # Old maintenance loops
    "origin/repokeeper/maintenance-20260818-loop"
    "origin/repokeeper/maintenance-20260818-loop2"
    "origin/repokeeper/maintenance-20260819-loop"
    "origin/repokeeper/maintenance-20260819-loop3"
)

echo "Branches to delete: ${#STALE_BRANCHES[@]}"
echo ""

for branch in "${STALE_BRANCHES[@]}"; do
    echo "Deleting: $branch"
    git push origin --delete "${branch#origin/}" 2>/dev/null || echo "  (already deleted or no permission)"
done

echo ""
echo "=== Cleanup Complete ==="
echo "Deleted ${#STALE_BRANCHES[@]} stale branches"
