/**
 * UI Strings Configuration
 *
 * Centralizes all hardcoded UI strings used in components.
 * This eliminates string literals scattered throughout the codebase.
 *
 * Usage:
 * ```typescript
 * import { UI_STRINGS } from '@/lib/config/ui-strings';
 *
 * // Instead of hardcoded string:
 * <button>Try Again</button>
 *
 * // Use centralized config:
 * <button>{UI_STRINGS.BUTTONS.RETRY}</button>
 * ```
 */

export const UI_STRINGS = {
  // Button labels
  BUTTONS: {
    RETRY: 'Try Again',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    DELETE: 'Delete',
    EDIT: 'Edit',
    CLOSE: 'Close',
    CONFIRM: 'Confirm',
    BACK: 'Back',
    NEXT: 'Next',
    SUBMIT: 'Submit',
    LOADING: 'Loading...',
    REFRESH: 'Refresh',
    COPY: 'Copy',
    SHARE: 'Share',
    DOWNLOAD: 'Download',
    UPLOAD: 'Upload',
    SEARCH: 'Search',
    FILTER: 'Filter',
    SORT: 'Sort',
    EXPAND: 'Expand',
    COLLAPSE: 'Collapse',
    SHOW_MORE: 'Show More',
    SHOW_LESS: 'Show Less',
    VIEW_ALL: 'View All',
    VIEW_DETAILS: 'View Details',
    GO_BACK: 'Go Back',
    GO_HOME: 'Go Home',
    SIGN_IN: 'Sign In',
    SIGN_UP: 'Sign Up',
    SIGN_OUT: 'Sign Out',
    FORGOT_PASSWORD: 'Forgot Password?',
    RESET_PASSWORD: 'Reset Password',
    CREATE_ACCOUNT: 'Create Account',
    CONTINUE: 'Continue',
    SKIP: 'Skip',
    FINISH: 'Finish',
    START: 'Start',
    PAUSE: 'Pause',
    RESUME: 'Resume',
    STOP: 'Stop',
    RETRY_CONNECTION: 'Retry Connection',
    CONTACT_SUPPORT: 'Contact Support',
    LEARN_MORE: 'Learn More',
    GET_STARTED: 'Get Started',
    WATCH_DEMO: 'Watch Demo',
    SEE_PRICING: 'See Pricing',
    REQUEST_DEMO: 'Request Demo',
    START_FREE: 'Start Free Trial',
    UPGRADE: 'Upgrade',
    DOWNGRADE: 'Downgrade',
    CANCEL_SUBSCRIPTION: 'Cancel Subscription',
    MANAGE_BILLING: 'Manage Billing',
    VIEW_INVOICES: 'View Invoices',
    DOWNLOAD_INVOICE: 'Download Invoice',
    EXPORT_DATA: 'Export Data',
    IMPORT_DATA: 'Import Data',
    CLEAR_DATA: 'Clear Data',
    RESET_DEFAULTS: 'Reset Defaults',
    APPLY_CHANGES: 'Apply Changes',
    DISCARD_CHANGES: 'Discard Changes',
    SAVE_CHANGES: 'Save Changes',
    SAVE_DRAFT: 'Save Draft',
    PUBLISH: 'Publish',
    UNPUBLISH: 'Unpublish',
    ARCHIVE: 'Archive',
    RESTORE: 'Restore',
    DUPLICATE: 'Duplicate',
    MOVE: 'Move',
    REORDER: 'Reorder',
    SELECT_ALL: 'Select All',
    DESELECT_ALL: 'Deselect All',
    INVERT_SELECTION: 'Invert Selection',
    BULK_ACTIONS: 'Bulk Actions',
    EXPORT_SELECTED: 'Export Selected',
    DELETE_SELECTED: 'Delete Selected',
    MARK_AS_READ: 'Mark as Read',
    MARK_AS_UNREAD: 'Mark as Unread',
    MARK_AS_DONE: 'Mark as Done',
    MARK_AS_INCOMPLETE: 'Mark as Incomplete',
    ADD_COMMENT: 'Add Comment',
    REPLY: 'Reply',
    FORWARD: 'Forward',
    REPORT: 'Report',
    BLOCK: 'Block',
    UNBLOCK: 'Unblock',
    MUTE: 'Mute',
    UNMUTE: 'Unmute',
    FOLLOW: 'Follow',
    UNFOLLOW: 'Unfollow',
    SUBSCRIBE: 'Subscribe',
    UNSUBSCRIBE: 'Unsubscribe',
    LIKE: 'Like',
    UNLIKE: 'Unlike',
    BOOKMARK: 'Bookmark',
    REMOVE_BOOKMARK: 'Remove Bookmark',
    SHARE_VIA_EMAIL: 'Share via Email',
    SHARE_VIA_LINK: 'Share via Link',
    COPY_LINK: 'Copy Link',
    OPEN_IN_NEW_TAB: 'Open in New Tab',
    PRINT: 'Print',
    REPORT_BUG: 'Report Bug',
    REQUEST_FEATURE: 'Request Feature',
    GIVE_FEEDBACK: 'Give Feedback',
    HELP_CENTER: 'Help Center',
    DOCUMENTATION: 'Documentation',
    COMMUNITY: 'Community',
    STATUS_PAGE: 'Status Page',
    TERMS_OF_SERVICE: 'Terms of Service',
    PRIVACY_POLICY: 'Privacy Policy',
    COOKIE_POLICY: 'Cookie Policy',
    LICENSE: 'License',
    ABOUT: 'About',
    CONTACT: 'Contact',
    CAREERS: 'Careers',
    BLOG: 'Blog',
    PRESS: 'Press',
    LEGAL: 'Legal',
    SECURITY: 'Security',
    COMPLIANCE: 'Compliance',
  },

  // Form labels
  FORM: {
    EMAIL_LABEL: 'Email',
    PASSWORD_LABEL: 'Password',
    CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    USERNAME_LABEL: 'Username',
    NAME_LABEL: 'Name',
    FIRST_NAME_LABEL: 'First Name',
    LAST_NAME_LABEL: 'Last Name',
    PHONE_LABEL: 'Phone',
    ADDRESS_LABEL: 'Address',
    CITY_LABEL: 'City',
    STATE_LABEL: 'State',
    COUNTRY_LABEL: 'Country',
    ZIP_CODE_LABEL: 'ZIP Code',
    COMPANY_LABEL: 'Company',
    JOB_TITLE_LABEL: 'Job Title',
    WEBSITE_LABEL: 'Website',
    DESCRIPTION_LABEL: 'Description',
    TITLE_LABEL: 'Title',
    SUBJECT_LABEL: 'Subject',
    MESSAGE_LABEL: 'Message',
    COMMENT_LABEL: 'Comment',
    SEARCH_LABEL: 'Search',
    FILTER_LABEL: 'Filter',
    SORT_LABEL: 'Sort',
    DATE_LABEL: 'Date',
    TIME_LABEL: 'Time',
    START_DATE_LABEL: 'Start Date',
    END_DATE_LABEL: 'End Date',
    CATEGORY_LABEL: 'Category',
    TAG_LABEL: 'Tags',
    STATUS_LABEL: 'Status',
    PRIORITY_LABEL: 'Priority',
    ASSIGNEE_LABEL: 'Assignee',
    DUE_DATE_LABEL: 'Due Date',
    ESTIMATED_HOURS_LABEL: 'Estimated Hours',
    ACTUAL_HOURS_LABEL: 'Actual Hours',
    BUDGET_LABEL: 'Budget',
    COST_LABEL: 'Cost',
    PRICE_LABEL: 'Price',
    QUANTITY_LABEL: 'Quantity',
    AMOUNT_LABEL: 'Amount',
    TOTAL_LABEL: 'Total',
    SUBTOTAL_LABEL: 'Subtotal',
    TAX_LABEL: 'Tax',
    DISCOUNT_LABEL: 'Discount',
    SHIPPING_LABEL: 'Shipping',
    PAYMENT_METHOD_LABEL: 'Payment Method',
    CARD_NUMBER_LABEL: 'Card Number',
    EXPIRY_DATE_LABEL: 'Expiry Date',
    CVV_LABEL: 'CVV',
    BILLING_ADDRESS_LABEL: 'Billing Address',
    SHIPPING_ADDRESS_LABEL: 'Shipping Address',
    SAME_AS_BILLING_LABEL: 'Same as billing address',
    SAVE_ADDRESS_LABEL: 'Save this address',
    DEFAULT_ADDRESS_LABEL: 'Set as default address',
    NOTIFICATION_PREFERENCES_LABEL: 'Notification Preferences',
    EMAIL_NOTIFICATIONS_LABEL: 'Email Notifications',
    PUSH_NOTIFICATIONS_LABEL: 'Push Notifications',
    SMS_NOTIFICATIONS_LABEL: 'SMS Notifications',
    MARKETING_EMAILS_LABEL: 'Marketing Emails',
    NEWSLETTER_LABEL: 'Subscribe to newsletter',
    TERMS_AGREEMENT_LABEL: 'I agree to the Terms of Service',
    PRIVACY_AGREEMENT_LABEL: 'I agree to the Privacy Policy',
    AGE_VERIFICATION_LABEL: 'I am at least 18 years old',
    CAPTCHA_LABEL: 'Please complete the CAPTCHA',
    UPLOAD_LABEL: 'Upload File',
    DRAG_AND_DROP_LABEL: 'Drag and drop files here',
    OR_LABEL: 'or',
    BROWSE_FILES_LABEL: 'Browse files',
    MAX_FILE_SIZE_LABEL: 'Maximum file size: {size}',
    ALLOWED_FILE_TYPES_LABEL: 'Allowed file types: {types}',
  },

  // Placeholder text
  PLACEHOLDERS: {
    EMAIL_PLACEHOLDER: 'Enter your email',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm your password',
    USERNAME_PLACEHOLDER: 'Enter your username',
    NAME_PLACEHOLDER: 'Enter your name',
    SEARCH_PLACEHOLDER: 'Search...',
    FILTER_PLACEHOLDER: 'Filter by...',
    SORT_PLACEHOLDER: 'Sort by...',
    DATE_PLACEHOLDER: 'Select date',
    TIME_PLACEHOLDER: 'Select time',
    MESSAGE_PLACEHOLDER: 'Enter your message',
    COMMENT_PLACEHOLDER: 'Add a comment...',
    DESCRIPTION_PLACEHOLDER: 'Enter description',
    TITLE_PLACEHOLDER: 'Enter title',
    SUBJECT_PLACEHOLDER: 'Enter subject',
    PHONE_PLACEHOLDER: 'Enter phone number',
    ADDRESS_PLACEHOLDER: 'Enter address',
    CITY_PLACEHOLDER: 'Enter city',
    STATE_PLACEHOLDER: 'Enter state',
    COUNTRY_PLACEHOLDER: 'Select country',
    ZIP_CODE_PLACEHOLDER: 'Enter ZIP code',
    COMPANY_PLACEHOLDER: 'Enter company name',
    JOB_TITLE_PLACEHOLDER: 'Enter job title',
    WEBSITE_PLACEHOLDER: 'Enter website URL',
    CARD_NUMBER_PLACEHOLDER: '1234 5678 9012 3456',
    EXPIRY_DATE_PLACEHOLDER: 'MM/YY',
    CVV_PLACEHOLDER: '123',
    BILLING_ADDRESS_PLACEHOLDER: 'Enter billing address',
    SHIPPING_ADDRESS_PLACEHOLDER: 'Enter shipping address',
    CATEGORY_PLACEHOLDER: 'Select category',
    TAG_PLACEHOLDER: 'Add tags...',
    STATUS_PLACEHOLDER: 'Select status',
    PRIORITY_PLACEHOLDER: 'Select priority',
    ASSIGNEE_PLACEHOLDER: 'Select assignee',
    DUE_DATE_PLACEHOLDER: 'Select due date',
    ESTIMATED_HOURS_PLACEHOLDER: 'Enter estimated hours',
    ACTUAL_HOURS_PLACEHOLDER: 'Enter actual hours',
    BUDGET_PLACEHOLDER: 'Enter budget',
    COST_PLACEHOLDER: 'Enter cost',
    PRICE_PLACEHOLDER: 'Enter price',
    QUANTITY_PLACEHOLDER: 'Enter quantity',
    AMOUNT_PLACEHOLDER: 'Enter amount',
    TOTAL_PLACEHOLDER: 'Total',
    SUBTOTAL_PLACEHOLDER: 'Subtotal',
    TAX_PLACEHOLDER: 'Tax',
    DISCOUNT_PLACEHOLDER: 'Discount',
    SHIPPING_PLACEHOLDER: 'Shipping',
    PAYMENT_METHOD_PLACEHOLDER: 'Select payment method',
    UPLOAD_PLACEHOLDER: 'Choose file to upload',
    DRAG_AND_DROP_PLACEHOLDER: 'Drag and drop files here',
    OR_PLACEHOLDER: 'or',
    BROWSE_FILES_PLACEHOLDER: 'Browse files',
    MAX_FILE_SIZE_PLACEHOLDER: 'Maximum file size: {size}',
    ALLOWED_FILE_TYPES_PLACEHOLDER: 'Allowed file types: {types}',
  },

  // Error messages
  ERRORS: {
    REQUIRED_FIELD: 'This field is required',
    INVALID_EMAIL: 'Please enter a valid email address',
    INVALID_PASSWORD: 'Password must be at least 8 characters',
    PASSWORD_MISMATCH: 'Passwords do not match',
    INVALID_PHONE: 'Please enter a valid phone number',
    INVALID_URL: 'Please enter a valid URL',
    INVALID_DATE: 'Please enter a valid date',
    INVALID_TIME: 'Please enter a valid time',
    INVALID_NUMBER: 'Please enter a valid number',
    INVALID_FORMAT: 'Invalid format',
    TOO_SHORT: 'This field is too short',
    TOO_LONG: 'This field is too long',
    TOO_SMALL: 'Value is too small',
    TOO_LARGE: 'Value is too large',
    NEGATIVE_NOT_ALLOWED: 'Negative values are not allowed',
    ZERO_NOT_ALLOWED: 'Zero is not allowed',
    FILE_TOO_LARGE: 'File is too large',
    INVALID_FILE_TYPE: 'Invalid file type',
    UPLOAD_FAILED: 'Upload failed',
    NETWORK_ERROR: 'Network error occurred',
    SERVER_ERROR: 'Server error occurred',
    TIMEOUT_ERROR: 'Request timed out',
    AUTHENTICATION_ERROR: 'Authentication error',
    AUTHORIZATION_ERROR: 'Authorization error',
    NOT_FOUND: 'Resource not found',
    CONFLICT: 'Resource already exists',
    RATE_LIMITED: 'Too many requests',
    VALIDATION_ERROR: 'Validation error',
    UNKNOWN_ERROR: 'An unknown error occurred',
    TRY_AGAIN: 'Please try again',
    CONTACT_SUPPORT: 'Please contact support',
    SESSION_EXPIRED: 'Your session has expired',
    LOG_IN_AGAIN: 'Please log in again',
    PERMISSION_DENIED: 'You do not have permission',
    ACCESS_DENIED: 'Access denied',
    ACCOUNT_LOCKED: 'Your account has been locked',
    PASSWORD_EXPIRED: 'Your password has expired',
    EMAIL_NOT_VERIFIED: 'Please verify your email',
    PHONE_NOT_VERIFIED: 'Please verify your phone number',
    TWO_FACTOR_REQUIRED: 'Two-factor authentication required',
    INVALID_TWO_FACTOR_CODE: 'Invalid two-factor code',
    BACKUP_CODES_REQUIRED: 'Please enter a backup code',
    INVALID_BACKUP_CODE: 'Invalid backup code',
    ACCOUNT_DEACTIVATED: 'Your account has been deactivated',
    ACCOUNT_SUSPENDED: 'Your account has been suspended',
    ACCOUNT_DELETED: 'Your account has been deleted',
    MAINTENANCE_MODE: 'System is in maintenance mode',
    FEATURE_UNAVAILABLE: 'This feature is currently unavailable',
    BETA_FEATURE: 'This is a beta feature',
    COMING_SOON: 'This feature is coming soon',
    NOT_IMPLEMENTED: 'This feature is not yet implemented',
    DEPRECATED: 'This feature is deprecated',
    UNSUPPORTED_BROWSER: 'Your browser is not supported',
    COOKIES_DISABLED: 'Please enable cookies',
    JAVASCRIPT_DISABLED: 'Please enable JavaScript',
    LOCAL_STORAGE_DISABLED: 'Please enable local storage',
    AD_BLOCKER_DETECTED: 'Ad blocker detected',
    VPN_DETECTED: 'VPN detected',
    BOT_DETECTED: 'Bot activity detected',
    SUSPICIOUS_ACTIVITY: 'Suspicious activity detected',
    FRAUD_DETECTED: 'Fraud detected',
    ACCOUNT_COMPROMISED: 'Your account may be compromised',
    CHANGE_PASSWORD_NOW: 'Please change your password immediately',
    REVIEW_SECURITY_SETTINGS: 'Please review your security settings',
  },

  // Success messages
  SUCCESS: {
    SAVED: 'Changes saved successfully',
    UPDATED: 'Updated successfully',
    DELETED: 'Deleted successfully',
    CREATED: 'Created successfully',
    COPIED: 'Copied to clipboard',
    SENT: 'Sent successfully',
    RECEIVED: 'Received successfully',
    DOWNLOADED: 'Downloaded successfully',
    UPLOADED: 'Uploaded successfully',
    SHARED: 'Shared successfully',
    SUBSCRIBED: 'Subscribed successfully',
    UNSUBSCRIBED: 'Unsubscribed successfully',
    FOLLOWED: 'Followed successfully',
    UNFOLLOWED: 'Unfollowed successfully',
    BOOKMARKED: 'Bookmarked successfully',
    REMOVED_BOOKMARK: 'Bookmark removed',
    LIKED: 'Liked successfully',
    UNLIKED: 'Unlike successful',
    COMMENT_ADDED: 'Comment added successfully',
    COMMENT_UPDATED: 'Comment updated successfully',
    COMMENT_DELETED: 'Comment deleted successfully',
    REPLY_ADDED: 'Reply added successfully',
    REPLY_UPDATED: 'Reply updated successfully',
    REPLY_DELETED: 'Reply deleted successfully',
    REPORT_SUBMITTED: 'Report submitted successfully',
    FEEDBACK_SUBMITTED: 'Feedback submitted successfully',
    CONTACT_SUBMITTED: 'Contact form submitted successfully',
    NEWSLETTER_SUBSCRIBED: 'Subscribed to newsletter successfully',
    TERMS_ACCEPTED: 'Terms accepted successfully',
    PRIVACY_ACCEPTED: 'Privacy policy accepted successfully',
    AGE_VERIFIED: 'Age verified successfully',
    CAPTCHA_VERIFIED: 'CAPTCHA verified successfully',
    FILE_UPLOADED: 'File uploaded successfully',
    FILES_UPLOADED: 'Files uploaded successfully',
    IMPORT_SUCCESSFUL: 'Import completed successfully',
    EXPORT_SUCCESSFUL: 'Export completed successfully',
    BACKUP_SUCCESSFUL: 'Backup completed successfully',
    RESTORE_SUCCESSFUL: 'Restore completed successfully',
    SYNC_SUCCESSFUL: 'Sync completed successfully',
    MIGRATION_SUCCESSFUL: 'Migration completed successfully',
    DEPLOYMENT_SUCCESSFUL: 'Deployment completed successfully',
    ROLLBACK_SUCCESSFUL: 'Rollback completed successfully',
    CONFIGURATION_UPDATED: 'Configuration updated successfully',
    SETTINGS_SAVED: 'Settings saved successfully',
    PROFILE_UPDATED: 'Profile updated successfully',
    AVATAR_UPLOADED: 'Avatar uploaded successfully',
    PASSWORD_CHANGED: 'Password changed successfully',
    EMAIL_CHANGED: 'Email address changed successfully',
    PHONE_CHANGED: 'Phone number changed successfully',
    TWO_FACTOR_ENABLED: 'Two-factor authentication enabled',
    TWO_FACTOR_DISABLED: 'Two-factor authentication disabled',
    BACKUP_CODES_GENERATED: 'Backup codes generated successfully',
    SESSION_REVOKED: 'Session revoked successfully',
    ALL_SESSIONS_REVOKED: 'All sessions revoked successfully',
    ACCOUNT_DELETED: 'Account deleted successfully',
    ACCOUNT_DEACTIVATED: 'Account deactivated successfully',
    ACCOUNT_ACTIVATED: 'Account activated successfully',
    ACCOUNT_SUSPENDED: 'Account suspended successfully',
    ACCOUNT_REACTIVATED: 'Account reactivated successfully',
    BAN_LIFTED: 'Ban lifted successfully',
    BLOCK_REMOVED: 'Block removed successfully',
    UNBLOCK_SUCCESSFUL: 'Unblocked successfully',
    MUTE_REMOVED: 'Unmuted successfully',
    NOTIFICATION_READ: 'Notification marked as read',
    ALL_NOTIFICATIONS_READ: 'All notifications marked as read',
    TASK_COMPLETED: 'Task completed successfully',
    TASK_REOPENED: 'Task reopened successfully',
    TASK_ARCHIVED: 'Task archived successfully',
    TASK_RESTORED: 'Task restored successfully',
    IDEA_PUBLISHED: 'Idea published successfully',
    IDEA_UNPUBLISHED: 'Idea unpublished successfully',
    IDEA_ARCHIVED: 'Idea archived successfully',
    IDEA_RESTORED: 'Idea restored successfully',
    IDEA_DUPLICATED: 'Idea duplicated successfully',
    IDEA_SHARED: 'Idea shared successfully',
    IDEA_EXPORTED: 'Idea exported successfully',
    IDEA_IMPORTED: 'Idea imported successfully',
    BLUEPRINT_GENERATED: 'Blueprint generated successfully',
    BLUEPRINT_UPDATED: 'Blueprint updated successfully',
    BLUEPRINT_EXPORTED: 'Blueprint exported successfully',
    BLUEPRINT_SHARED: 'Blueprint shared successfully',
    ROADMAP_GENERATED: 'Roadmap generated successfully',
    ROADMAP_UPDATED: 'Roadmap updated successfully',
    ROADMAP_EXPORTED: 'Roadmap exported successfully',
    ROADMAP_SHARED: 'Roadmap shared successfully',
    TASKS_GENERATED: 'Tasks generated successfully',
    TASKS_UPDATED: 'Tasks updated successfully',
    TASKS_EXPORTED: 'Tasks exported successfully',
    TASKS_SHARED: 'Tasks shared successfully',
    TIMELINE_GENERATED: 'Timeline generated successfully',
    TIMELINE_UPDATED: 'Timeline updated successfully',
    TIMELINE_EXPORTED: 'Timeline exported successfully',
    TIMELINE_SHARED: 'Timeline shared successfully',
  },

  // Warning messages
  WARNINGS: {
    UNSAVED_CHANGES: 'You have unsaved changes',
    CONFIRM_LEAVE: 'Are you sure you want to leave?',
    CONFIRM_DELETE: 'Are you sure you want to delete this?',
    CONFIRM_DEACTIVATE: 'Are you sure you want to deactivate your account?',
    CONFIRM_CANCEL_SUBSCRIPTION:
      'Are you sure you want to cancel your subscription?',
    CONFIRM_BLOCK: 'Are you sure you want to block this user?',
    CONFIRM_UNBLOCK: 'Are you sure you want to unblock this user?',
    CONFIRM_MUTE: 'Are you sure you want to mute this user?',
    CONFIRM_UNMUTE: 'Are you sure you want to unmute this user?',
    CONFIRM_FOLLOW: 'Are you sure you want to follow this user?',
    CONFIRM_UNFOLLOW: 'Are you sure you want to unfollow this user?',
    CONFIRM_SUBSCRIBE: 'Are you sure you want to subscribe?',
    CONFIRM_UNSUBSCRIBE: 'Are you sure you want to unsubscribe?',
    CONFIRM_REPORT: 'Are you sure you want to report this?',
    CONFIRM_BLOCK_USER: 'Are you sure you want to block this user?',
    CONFIRM_UNBLOCK_USER: 'Are you sure you want to unblock this user?',
    CONFIRM_MUTE_USER: 'Are you sure you want to mute this user?',
    CONFIRM_UNMUTE_USER: 'Are you sure you want to unmute this user?',
    CONFIRM_FOLLOW_USER: 'Are you sure you want to follow this user?',
    CONFIRM_UNFOLLOW_USER: 'Are you sure you want to unfollow this user?',
    CONFIRM_SUBSCRIBE_USER: 'Are you sure you want to subscribe to this user?',
    CONFIRM_UNSUBSCRIBE_USER:
      'Are you sure you want to unsubscribe from this user?',
    CONFIRM_REPORT_USER: 'Are you sure you want to report this user?',
    CONFIRM_REPORT_CONTENT: 'Are you sure you want to report this content?',
    CONFIRM_DELETE_ACCOUNT:
      'Are you sure you want to delete your account? This action cannot be undone.',
    CONFIRM_DEACTIVATE_ACCOUNT:
      'Are you sure you want to deactivate your account? You can reactivate it later.',
    CONFIRM_CANCEL_SUBSCRIPTION_WARNING:
      'Cancelling your subscription will remove access to premium features.',
    CONFIRM_DOWNGRADE: 'Downgrading will remove access to premium features.',
    CONFIRM_EXPORT_DATA:
      'This will export all your data. This may take a while.',
    CONFIRM_IMPORT_DATA:
      'This will import data from the selected file. Existing data may be overwritten.',
    CONFIRM_CLEAR_DATA:
      'This will clear all your data. This action cannot be undone.',
    CONFIRM_RESET_DEFAULTS: 'This will reset all settings to default values.',
    CONFIRM_APPLY_CHANGES: 'Are you sure you want to apply these changes?',
    CONFIRM_DISCARD_CHANGES: 'Are you sure you want to discard your changes?',
    CONFIRM_SAVE_CHANGES: 'Are you sure you want to save these changes?',
    CONFIRM_PUBLISH: 'Are you sure you want to publish this?',
    CONFIRM_UNPUBLISH: 'Are you sure you want to unpublish this?',
    CONFIRM_ARCHIVE: 'Are you sure you want to archive this?',
    CONFIRM_RESTORE: 'Are you sure you want to restore this?',
    CONFIRM_DUPLICATE: 'Are you sure you want to duplicate this?',
    CONFIRM_MOVE: 'Are you sure you want to move this?',
    CONFIRM_REORDER: 'Are you sure you want to reorder this?',
    CONFIRM_SELECT_ALL: 'Are you sure you want to select all items?',
    CONFIRM_DESELECT_ALL: 'Are you sure you want to deselect all items?',
    CONFIRM_INVERT_SELECTION: 'Are you sure you want to invert the selection?',
    CONFIRM_BULK_ACTIONS:
      'Are you sure you want to perform bulk actions on selected items?',
    CONFIRM_EXPORT_SELECTED: 'Are you sure you want to export selected items?',
    CONFIRM_DELETE_SELECTED: 'Are you sure you want to delete selected items?',
    CONFIRM_MARK_AS_READ: 'Are you sure you want to mark as read?',
    CONFIRM_MARK_AS_UNREAD: 'Are you sure you want to mark as unread?',
    CONFIRM_MARK_AS_DONE: 'Are you sure you want to mark as done?',
    CONFIRM_MARK_AS_INCOMPLETE: 'Are you sure you want to mark as incomplete?',
    CONFIRM_ADD_COMMENT: 'Are you sure you want to add this comment?',
    CONFIRM_REPLY: 'Are you sure you want to reply to this?',
    CONFIRM_FORWARD: 'Are you sure you want to forward this?',
    CONFIRM_REPORT_BUG: 'Are you sure you want to report this bug?',
    CONFIRM_REQUEST_FEATURE: 'Are you sure you want to request this feature?',
    CONFIRM_GIVE_FEEDBACK: 'Are you sure you want to give feedback?',
  },

  // Info messages
  INFO: {
    LOADING: 'Loading...',
    PROCESSING: 'Processing...',
    SAVING: 'Saving...',
    SENDING: 'Sending...',
    UPLOADING: 'Uploading...',
    DOWNLOADING: 'Downloading...',
    SYNCING: 'Syncing...',
    CONNECTING: 'Connecting...',
    RECONNECTING: 'Reconnecting...',
    RETRYING: 'Retrying...',
    WAITING: 'Waiting...',
    PLEASE_WAIT: 'Please wait...',
    ONE_MOMENT: 'One moment...',
    ALMOST_DONE: 'Almost done...',
    JUST_A_SECOND: 'Just a second...',
    NO_RESULTS: 'No results found',
    NO_DATA: 'No data available',
    NO_ITEMS: 'No items to display',
    EMPTY_STATE: 'Nothing here yet',
    COMING_SOON: 'Coming soon',
    MAINTENANCE: 'Under maintenance',
    FEATURE_UNAVAILABLE: 'Feature temporarily unavailable',
    BETA: 'Beta',
    NEW: 'New',
    UPDATED: 'Updated',
    DEPRECATED: 'Deprecated',
    LEGACY: 'Legacy',
    EXPIRED: 'Expired',
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    PENDING: 'Pending',
    COMPLETED: 'Completed',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled',
    PAUSED: 'Paused',
    RESUMED: 'Resumed',
    STOPPED: 'Stopped',
    RUNNING: 'Running',
    QUEUED: 'Queued',
    SUCCESSFUL: 'Successful',
    UNSUCCESSFUL: 'Unsuccessful',
    PARTIAL: 'Partial',
    IN_PROGRESS: 'In Progress',
    NOT_STARTED: 'Not Started',
    ON_TRACK: 'On Track',
    AT_RISK: 'At Risk',
    BEHIND: 'Behind',
    AHEAD: 'Ahead',
    ON_SCHEDULE: 'On Schedule',
    DELAYED: 'Delayed',
    OVERDUE: 'Overdue',
    DUE_TODAY: 'Due Today',
    DUE_TOMORROW: 'Due Tomorrow',
    DUE_THIS_WEEK: 'Due This Week',
    DUE_NEXT_WEEK: 'Due Next Week',
    DUE_THIS_MONTH: 'Due This Month',
    DUE_NEXT_MONTH: 'Due Next Month',
    DUE_SOON: 'Due Soon',
    DUE_LATER: 'Due Later',
    DUE_DATE: 'Due Date',
    CREATED_DATE: 'Created Date',
    UPDATED_DATE: 'Updated Date',
    MODIFIED_DATE: 'Modified Date',
    LAST_UPDATED: 'Last Updated',
    LAST_MODIFIED: 'Last Modified',
    LAST_SYNCED: 'Last Synced',
    LAST_LOGIN: 'Last Login',
    LAST_ACTIVE: 'Last Active',
    MEMBER_SINCE: 'Member Since',
    ACCOUNT_AGE: 'Account Age',
    SUBSCRIPTION_STATUS: 'Subscription Status',
    BILLING_STATUS: 'Billing Status',
    PAYMENT_STATUS: 'Payment Status',
    INVOICE_STATUS: 'Invoice Status',
    ORDER_STATUS: 'Order Status',
    SHIPPING_STATUS: 'Shipping Status',
    DELIVERY_STATUS: 'Delivery Status',
    RETURN_STATUS: 'Return Status',
    REFUND_STATUS: 'Refund Status',
    EXCHANGE_STATUS: 'Exchange Status',
    WARRANTY_STATUS: 'Warranty Status',
    SUPPORT_STATUS: 'Support Status',
    TICKET_STATUS: 'Ticket Status',
    ISSUE_STATUS: 'Issue Status',
    BUG_STATUS: 'Bug Status',
    FEATURE_STATUS: 'Feature Status',
    PROJECT_STATUS: 'Project Status',
    TASK_STATUS: 'Task Status',
    GOAL_STATUS: 'Goal Status',
    OBJECTIVE_STATUS: 'Objective Status',
    KEY_RESULT_STATUS: 'Key Result Status',
    MILESTONE_STATUS: 'Milestone Status',
    DEADLINE_STATUS: 'Deadline Status',
    SPRINT_STATUS: 'Sprint Status',
    RELEASE_STATUS: 'Release Status',
    DEPLOYMENT_STATUS: 'Deployment Status',
    BUILD_STATUS: 'Build Status',
    TEST_STATUS: 'Test Status',
    REVIEW_STATUS: 'Review Status',
    APPROVAL_STATUS: 'Approval Status',
    PUBLISH_STATUS: 'Publish Status',
    LIVE_STATUS: 'Live Status',
    MAINTENANCE_STATUS: 'Maintenance Status',
    INCIDENT_STATUS: 'Incident Status',
    OUTAGE_STATUS: 'Outage Status',
    UPTIME_STATUS: 'Uptime Status',
    PERFORMANCE_STATUS: 'Performance Status',
    SECURITY_STATUS: 'Security Status',
    COMPLIANCE_STATUS: 'Compliance Status',
    AUDIT_STATUS: 'Audit Status',
    BACKUP_STATUS: 'Backup Status',
    RESTORE_STATUS: 'Restore Status',
    MIGRATION_STATUS: 'Migration Status',
    SYNC_STATUS: 'Sync Status',
    INTEGRATION_STATUS: 'Integration Status',
    CONNECTION_STATUS: 'Connection Status',
    NETWORK_STATUS: 'Network Status',
    SERVER_STATUS: 'Server Status',
    DATABASE_STATUS: 'Database Status',
    CACHE_STATUS: 'Cache Status',
    QUEUE_STATUS: 'Queue Status',
    WORKER_STATUS: 'Worker Status',
    CRON_STATUS: 'Cron Status',
    SCHEDULE_STATUS: 'Schedule Status',
    TIMER_STATUS: 'Timer Status',
    COUNTDOWN_STATUS: 'Countdown Status',
    NOTIFICATION_STATUS: 'Notification Status',
    MESSAGE_STATUS: 'Message Status',
    EMAIL_STATUS: 'Email Status',
    SMS_STATUS: 'SMS Status',
    PUSH_STATUS: 'Push Status',
    WEBHOOK_STATUS: 'Webhook Status',
    API_STATUS: 'API Status',
    SERVICE_STATUS: 'Service Status',
    HEALTH_STATUS: 'Health Status',
    AVAILABILITY_STATUS: 'Availability Status',
    LATENCY_STATUS: 'Latency Status',
    THROUGHPUT_STATUS: 'Throughput Status',
    ERROR_RATE_STATUS: 'Error Rate Status',
    SUCCESS_RATE_STATUS: 'Success Rate Status',
    RESPONSE_TIME_STATUS: 'Response Time Status',
    REQUEST_RATE_STATUS: 'Request Rate Status',
    CONNECTION_RATE_STATUS: 'Connection Rate Status',
    BANDWIDTH_STATUS: 'Bandwidth Status',
    STORAGE_STATUS: 'Storage Status',
    MEMORY_STATUS: 'Memory Status',
    CPU_STATUS: 'CPU Status',
    DISK_STATUS: 'Disk Status',
    NETWORK_IO_STATUS: 'Network I/O Status',
    DISK_IO_STATUS: 'Disk I/O Status',
    GPU_STATUS: 'GPU Status',
  },
} as const;

// Type for UI strings
export type UiStrings = typeof UI_STRINGS;

// Helper function to get nested UI string
export function getUiString(category: keyof UiStrings, key: string): string {
  const categoryStrings = UI_STRINGS[category];
  if (categoryStrings && typeof categoryStrings === 'object') {
    const str = (categoryStrings as Record<string, string>)[key];
    if (typeof str === 'string') {
      return str;
    }
  }
  return '';
}

// Helper function to get UI string with interpolation
export function getUiStringWithParams(
  category: keyof UiStrings,
  key: string,
  params: Record<string, string | number>
): string {
  let str = getUiString(category, key);
  for (const [paramKey, paramValue] of Object.entries(params)) {
    str = str.replace(`{${paramKey}}`, String(paramValue));
  }
  return str;
}

// Common UI string constants for quick access
export const BUTTON_LABELS = UI_STRINGS.BUTTONS;
export const FORM_LABELS = UI_STRINGS.FORM;
export const PLACEHOLDER_TEXT = UI_STRINGS.PLACEHOLDERS;
export const ERROR_MESSAGES = UI_STRINGS.ERRORS;
export const SUCCESS_MESSAGES = UI_STRINGS.SUCCESS;
export const WARNING_MESSAGES = UI_STRINGS.WARNINGS;
export const INFO_MESSAGES = UI_STRINGS.INFO;
